# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Project_Python\RDM_Office_Automation\UI\Sources\ui\addwarInformation_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1274, 828)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.projectName_Ledit = QtWidgets.QLineEdit(Form)
        self.projectName_Ledit.setMinimumSize(QtCore.QSize(0, 25))
        self.projectName_Ledit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.projectName_Ledit.setObjectName("projectName_Ledit")
        self.gridLayout.addWidget(self.projectName_Ledit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.projectNum_Ledit = QtWidgets.QLineEdit(Form)
        self.projectNum_Ledit.setMinimumSize(QtCore.QSize(0, 25))
        self.projectNum_Ledit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.projectNum_Ledit.setObjectName("projectNum_Ledit")
        self.gridLayout.addWidget(self.projectNum_Ledit, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.projectSpec_Ledit = QtWidgets.QLineEdit(Form)
        self.projectSpec_Ledit.setMinimumSize(QtCore.QSize(0, 25))
        self.projectSpec_Ledit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.projectSpec_Ledit.setObjectName("projectSpec_Ledit")
        self.gridLayout.addWidget(self.projectSpec_Ledit, 0, 5, 1, 1)
        self.search_btn = QtWidgets.QPushButton(Form)
        self.search_btn.setMinimumSize(QtCore.QSize(0, 28))
        self.search_btn.setMaximumSize(QtCore.QSize(16777215, 28))
        self.search_btn.setObjectName("search_btn")
        self.gridLayout.addWidget(self.search_btn, 0, 6, 1, 1)
        self.allChoose_Rad = QtWidgets.QRadioButton(Form)
        self.allChoose_Rad.setEnabled(False)
        self.allChoose_Rad.setMinimumSize(QtCore.QSize(0, 25))
        self.allChoose_Rad.setMaximumSize(QtCore.QSize(16777215, 25))
        self.allChoose_Rad.setObjectName("allChoose_Rad")
        self.gridLayout.addWidget(self.allChoose_Rad, 0, 7, 1, 1)
        self.inverse_Rad = QtWidgets.QRadioButton(Form)
        self.inverse_Rad.setEnabled(False)
        self.inverse_Rad.setMinimumSize(QtCore.QSize(0, 25))
        self.inverse_Rad.setMaximumSize(QtCore.QSize(16777215, 25))
        self.inverse_Rad.setObjectName("inverse_Rad")
        self.gridLayout.addWidget(self.inverse_Rad, 0, 8, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.waringIforma_Ledit = QtWidgets.QLineEdit(Form)
        self.waringIforma_Ledit.setEnabled(False)
        self.waringIforma_Ledit.setMinimumSize(QtCore.QSize(0, 25))
        self.waringIforma_Ledit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.waringIforma_Ledit.setObjectName("waringIforma_Ledit")
        self.gridLayout.addWidget(self.waringIforma_Ledit, 1, 1, 1, 5)
        self.commit_btn = QtWidgets.QPushButton(Form)
        self.commit_btn.setEnabled(False)
        self.commit_btn.setMinimumSize(QtCore.QSize(0, 28))
        self.commit_btn.setMaximumSize(QtCore.QSize(16777215, 28))
        self.commit_btn.setObjectName("commit_btn")
        self.gridLayout.addWidget(self.commit_btn, 1, 6, 1, 3)
        self.display_tab = QtWidgets.QTableView(Form)
        self.display_tab.setObjectName("display_tab")
        self.gridLayout.addWidget(self.display_tab, 2, 0, 1, 9)

        self.retranslateUi(Form)
        self.search_btn.clicked.connect(Form.search_btn_click)
        self.allChoose_Rad.clicked.connect(self.display_tab.selectAll)
        self.inverse_Rad.clicked.connect(Form.inverse_rad_checked)
        self.commit_btn.clicked.connect(Form.combit_btn_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "成品描述:"))
        self.label_2.setText(_translate("Form", "成品料号:"))
        self.label_3.setText(_translate("Form", "规格描述:"))
        self.search_btn.setText(_translate("Form", "查  询"))
        self.allChoose_Rad.setText(_translate("Form", "全选"))
        self.inverse_Rad.setText(_translate("Form", "反选"))
        self.label_4.setText(_translate("Form", "注意事项："))
        self.commit_btn.setText(_translate("Form", "提交"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
